### Melihat Semua Catatan
GET http://localhost:3000/api/notes

### Menambah Catatan Baru
POST http://localhost:3000/api/notes
Content-Type: application/json

{
    "judul": "Test dari api buat ss",
    "isi": "Ini membuat catatan yang dikirim dari api.rest."
}

### Mengedit Catatan (Ganti angka 1 dengan ID catatan yang ada)
PUT http://localhost:3000/api/notes/3
Content-Type: application/json

{
    "judul": "Test dari api buat ss",
    "isi": "Ini membuat catatan yang dikirim dari api.rest revisi."
}

### Menghapus Catatan (Ganti angka 1 dengan ID catatan)
DELETE http://localhost:3000/api/notes/3